"""
Crystallographic symmetry expansion for RABDAM.

This module produces the symmetry-expansion stage used by RABDAM before
unit-cell translation and packing-density calculation.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

import gemmi
import numpy as np

from input.reader import StructureMetadata
from structure.models import PreparedAtom, PreparedStructure


class CrystalSymmetryError(ValueError):
    """Raised when RABDAM cannot build crystallographic symmetry images."""


@dataclass(frozen=True)
class UnitCellParameters:
    """Unit-cell parameters in Angstroms and degrees."""

    a: float
    b: float
    c: float
    alpha: float
    beta: float
    gamma: float


@dataclass(frozen=True)
class SymmetryExpandedAtom:
    """
    One atom after applying crystallographic symmetry to the prepared structure.

    unit_cell_atom_index:
        One-based index in the symmetry-expanded unit-cell atom list.

    source_atom_index:
        Zero-based reader index of the original asymmetric-unit atom.

    symmetry_operation_index:
        One-based index of the space-group operation that generated this atom.

    symmetry_operation:
        Gemmi/CIF-style operation triplet, for example "x,y,z".

    is_identity_symmetry_operation:
        True when this atom was generated by the identity symmetry operation.
    """

    unit_cell_atom_index: int
    source_atom_index: int
    symmetry_operation_index: int
    symmetry_operation: str
    is_identity_symmetry_operation: bool
    x: float
    y: float
    z: float


@dataclass(frozen=True)
class SymmetryExpandedStructure:
    """Symmetry-expanded unit-cell coordinates for all cleaned atoms."""

    atoms: tuple[SymmetryExpandedAtom, ...]
    unit_cell: UnitCellParameters
    space_group_name: str
    operation_count: int


def expand_prepared_structure_by_symmetry(
    prepared_structure: PreparedStructure,
) -> SymmetryExpandedStructure:
    """
    Expand cleaned asymmetric-unit atoms using crystallographic symmetry.

    It expands prepared_structure.cleaned_atoms, not selected_atoms, because
    RABDAM builds the surrounding unit cell from the cleaned asymmetric unit
    before applying the BDamage atom-selection subset.

    Fractional coordinates generated by symmetry operations are not wrapped
    into [0, 1). This preserves the generated translated image for the later
    trimmed neighbour-box stage.
    """

    return expand_atoms_by_symmetry(
        atoms=prepared_structure.cleaned_atoms,
        metadata=prepared_structure.metadata,
    )


def expand_atoms_by_symmetry(
    *,
    atoms: Iterable[PreparedAtom],
    metadata: StructureMetadata,
) -> SymmetryExpandedStructure:
    """
    Expand cleaned asymmetric-unit atoms using metadata symmetry.
    """

    atom_tuple = tuple(atoms)

    if not atom_tuple:
        raise CrystalSymmetryError(
            "Cannot symmetry-expand an empty atom list."
        )

    unit_cell = unit_cell_from_metadata(metadata)
    gemmi_cell = make_gemmi_unit_cell(unit_cell)
    space_group = space_group_from_metadata(metadata)
    operations = tuple(space_group.operations())

    if not operations:
        raise CrystalSymmetryError(
            f"Space group {metadata.space_group!r} has no symmetry operations."
        )

    expanded_coordinates = _symmetry_expanded_coordinates(
        atoms=atom_tuple,
        gemmi_cell=gemmi_cell,
        operations=operations,
    )
    operation_triplets = tuple(operation.triplet() for operation in operations)
    operation_identity_flags = tuple(
        operation_triplet.replace(" ", "") == "x,y,z"
        for operation_triplet in operation_triplets
    )

    expanded_atoms: list[SymmetryExpandedAtom] = []
    for atom_index, atom in enumerate(atom_tuple):
        for operation_index, coordinates in enumerate(
            expanded_coordinates[atom_index],
            start=1,
        ):
            expanded_atoms.append(
                SymmetryExpandedAtom(
                    unit_cell_atom_index=len(expanded_atoms) + 1,
                    source_atom_index=atom.record.source_atom_index,
                    symmetry_operation_index=operation_index,
                    symmetry_operation=operation_triplets[operation_index - 1],
                    is_identity_symmetry_operation=(
                        operation_identity_flags[operation_index - 1]
                    ),
                    x=float(coordinates[0]),
                    y=float(coordinates[1]),
                    z=float(coordinates[2]),
                )
            )

    return SymmetryExpandedStructure(
        atoms=tuple(expanded_atoms),
        unit_cell=unit_cell,
        space_group_name=space_group.hm,
        operation_count=len(operations),
    )


def _symmetry_expanded_coordinates(
    *,
    atoms: tuple[PreparedAtom, ...],
    gemmi_cell: gemmi.UnitCell,
    operations: tuple[gemmi.Op, ...],
) -> np.ndarray:
    """
    Return atom-major, operation-major symmetry-expanded Cartesian coordinates.
    """

    cartesian_coordinates = np.asarray(
        [(atom.record.x, atom.record.y, atom.record.z) for atom in atoms],
        dtype=np.float64,
    )
    fractionalization_matrix = _gemmi_transform_matrix(gemmi_cell.frac)
    fractionalization_vector = _gemmi_transform_vector(gemmi_cell.frac)
    orthogonalization_matrix = _gemmi_transform_matrix(gemmi_cell.orth)
    orthogonalization_vector = _gemmi_transform_vector(gemmi_cell.orth)

    fractional_coordinates = (
        cartesian_coordinates @ fractionalization_matrix.T
        + fractionalization_vector
    )
    operation_rotations = np.asarray(
        [
            np.asarray(operation.rot, dtype=np.float64) / operation.DEN
            for operation in operations
        ],
        dtype=np.float64,
    )
    operation_translations = np.asarray(
        [
            np.asarray(operation.tran, dtype=np.float64) / operation.DEN
            for operation in operations
        ],
        dtype=np.float64,
    )

    transformed_fractional_coordinates = (
        np.einsum("ni,mji->nmj", fractional_coordinates, operation_rotations)
        + operation_translations[np.newaxis, :, :]
    )

    return (
        transformed_fractional_coordinates @ orthogonalization_matrix.T
        + orthogonalization_vector
    )


def _gemmi_transform_matrix(transform: Any) -> np.ndarray:
    """Return a Gemmi Transform matrix as a float64 NumPy array."""

    return np.asarray(transform.mat.tolist(), dtype=np.float64)


def _gemmi_transform_vector(transform: Any) -> np.ndarray:
    """Return a Gemmi Transform translation vector as a float64 NumPy array."""

    return np.asarray(
        (transform.vec.x, transform.vec.y, transform.vec.z),
        dtype=np.float64,
    )


def apply_operation_without_wrapping(
    operation: gemmi.Op,
    fractional: gemmi.Fractional,
) -> gemmi.Fractional:
    """
    Apply a space-group operation to fractional coordinates without wrapping.

    Do not call Fractional.wrap_to_unit() here. Wrapping can change which
    translated image falls inside the later trimmed neighbour box.
    """

    transformed = operation.apply_to_xyz(
        [fractional.x, fractional.y, fractional.z]
    )

    return gemmi.Fractional(
        float(transformed[0]),
        float(transformed[1]),
        float(transformed[2]),
    )


def unit_cell_from_metadata(metadata: StructureMetadata) -> UnitCellParameters:
    """
    Build validated unit-cell parameters from structure metadata.
    """

    unit_cell_a = metadata.unit_cell_a
    unit_cell_b = metadata.unit_cell_b
    unit_cell_c = metadata.unit_cell_c
    unit_cell_alpha = metadata.unit_cell_alpha
    unit_cell_beta = metadata.unit_cell_beta
    unit_cell_gamma = metadata.unit_cell_gamma

    if (
        unit_cell_a is None
        or unit_cell_b is None
        or unit_cell_c is None
        or unit_cell_alpha is None
        or unit_cell_beta is None
        or unit_cell_gamma is None
    ):
        raise CrystalSymmetryError(
            "Structure metadata is missing complete unit-cell parameters."
        )

    try:
        unit_cell = UnitCellParameters(
            a=float(unit_cell_a),
            b=float(unit_cell_b),
            c=float(unit_cell_c),
            alpha=float(unit_cell_alpha),
            beta=float(unit_cell_beta),
            gamma=float(unit_cell_gamma),
        )
    except (TypeError, ValueError) as error:
        raise CrystalSymmetryError(
            "Structure metadata contains non-numeric unit-cell parameters."
        ) from error

    if unit_cell.a <= 0 or unit_cell.b <= 0 or unit_cell.c <= 0:
        raise CrystalSymmetryError(
            f"Invalid unit-cell lengths: {unit_cell!r}."
        )

    angles = (unit_cell.alpha, unit_cell.beta, unit_cell.gamma)
    if not all(0 < angle < 180 for angle in angles):
        raise CrystalSymmetryError(
            f"Invalid unit-cell angles: {unit_cell!r}."
        )

    return unit_cell


def make_gemmi_unit_cell(unit_cell: UnitCellParameters) -> gemmi.UnitCell:
    """Return a Gemmi UnitCell from validated unit-cell parameters."""

    return gemmi.UnitCell(
        unit_cell.a,
        unit_cell.b,
        unit_cell.c,
        unit_cell.alpha,
        unit_cell.beta,
        unit_cell.gamma,
    )


def space_group_from_metadata(metadata: StructureMetadata) -> gemmi.SpaceGroup:
    """
    Resolve the metadata space-group name to a Gemmi SpaceGroup.
    """

    if metadata.space_group is None or not str(metadata.space_group).strip():
        raise CrystalSymmetryError(
            "Structure metadata is missing a space-group name."
        )

    space_group_name = normalize_space_group_name(metadata.space_group)
    space_group = gemmi.find_spacegroup_by_name(space_group_name)

    if space_group is None:
        raise CrystalSymmetryError(
            f"Gemmi could not recognize space group {metadata.space_group!r}."
        )

    return space_group


def normalize_space_group_name(space_group_name: str) -> str:
    """
    Normalize common quoting/spacing artifacts in space-group names.
    """

    cleaned = str(space_group_name).replace("'", "").replace('"', "")
    return " ".join(cleaned.split())


def coordinates_as_tuples(
    expanded_structure: SymmetryExpandedStructure,
) -> tuple[tuple[float, float, float], ...]:
    """
    Return only xyz coordinates from a symmetry-expanded structure.

    This helper makes it easy for translate.py/packing.py to consume the
    expanded coordinate array.
    """

    return tuple((atom.x, atom.y, atom.z) for atom in expanded_structure.atoms)
